### ISSUE TITLE
co-queue with async/await

### ISSUE THREAD

**Issue by reharik** [juliangruber/co-queue#4]
Hi, I'm looking at the code and I don't really see anything that has to do with co.  could I not have a while(true) that awaits Queue.next();
Thanks for the help.
R

**Comment by juliangruber** [comment]
This library returns thunks instead of promises. Co supports thunks, whereas I'm not sure the async/await implementation you use supports anything but promises.

**Comment by juliangruber** [comment]
I'm definitively up for returning promises instead, so that it works with async/await too.

**Comment by reharik** [comment]
I'm playing with it now.  
Perhaps I'm doing something wrong but I have 
`this.queue.push({
                event,
                handlerFunction
            });
then in an other func

  var value = await this.queue.next();
             console.log('==========value=========');
             console.log(value.toString());
             console.log('==========END value=========');
`

what the console says is 
`
==========value=========
function (fn){
    if (self.buf.length) return fn(null, self.buf.shift());
    self.fns.push(fn);
  }
==========END value=========

obviously my markdown sucks.  
But shouldn't the value be an object with event and handlerFunction?
thx

**Comment by juliangruber** [comment]
(edited your markdown)

**Comment by juliangruber** [comment]
yep, that means that this module needs to be updated to return a promise [here](https://github.com/juliangruber/co-queue/blob/master/index.js#L49)

**Comment by reharik** [comment]
hmmm, I feel like I should understand the difference between a thunk and a promise better. 
Should I not be able to just call value() and get my value? I tried that and I still got a function back.
Regardless is there an advantage to returning a thunk here? or would it be just as good plus able to work with async/await if it was a promise.
If it's all the same I'll make the change and submit a pr

**Comment by reharik** [comment]
hmm, seems like one might right this differently if using promises.  for instance
```js
Queue.prototype.start = function() { this.next(); }
Queue.prototype.next = function() { if(this.buf.length) { return Promise.resolve(this.buf.shift()); }
Queue.prototype.push = function(data) { if(!this.buf.length) {this.buf.push(data); this.next();} else {this.buf.push(data); } }
```
not to elegant at the end but would that work?
r

**Comment by juliangruber** [comment]
i made it return promises, can you try version 3.0.0?

**Comment by reharik** [comment]
Im sorry I"ve been pulled off of that project for a while. I will check it
when(if) they let me back on it.
thanks for your help.
r

**Comment by juliangruber** [comment]
ok, closing for now then
